num = int(input('Entre o numero que quer ver a tabuada: '))
print('-'*12)
print('{} x {} = {}'.format(1,num,num*1))
print('{} x {} = {}'.format(2,num,num*2))
print('{} x {} = {}'.format(3,num,num*3))
print('{} x {} = {}'.format(4,num,num*4))
print('{} x {} = {}'.format(5,num,num*5))
print('{} x {} = {}'.format(6,num,num*6))
print('{} x {} = {}'.format(7,num,num*7))
print('{} x {} = {}'.format(8,num,num*8))
print('{} x {} = {}'.format(9,num,num*9))
print('{} x {} = {}'.format(10,num,num*10))
print('-'*12)